### PR TITLE
Instant Download

### PR DESCRIPTION
**Pull request by felixs-alt**
Uses a fetch request to the cobalt.tools api to instantly get the video/audio

### CODE REVIEW

**Comment by dimdenGD** [comment]
Looks good to me, but using `instance` for storing new url will break extension for everyone who has custom instance set

**Comment by dimdenGD** [comment]
Oh it doesn't even look at instance set too

**Comment by felixs-alt** [comment]
im sorry it is my first time editing chrome extensions

**Comment by felixs-alt** [comment]
i think i fixed it there

**Comment by dimdenGD** [comment]
You should change `instance` to any other name so on update it doesnt break but resets to default instead

**Comment by felixs-alt** [comment]
i thought i changed the default instance to api.cobalt.tools

**Comment by dimdenGD** [comment]
That only changes it for new users but if someone set it to something else it'll break because they'll need to add `api.` to their instance

**Comment by felixs-alt** [comment]
i think that is it

**Pull request merged**
