### PR TITLE
Add optional permissions to manifest.json

### PR DESCRIPTION
**Pull request by Inclushe**
I can't seem to properly test this as I'm getting `background.service_worker is currently disabled` when trying to load this in `about:debugging`, however, removing the service worker only when testing seems to show that additional permission. I'm not sure if this will be resolved when submitting to the Firefox store.

### CODE REVIEW

**Comment by dimdenGD** [comment]
You should test it by using Firefox for Developers and adding it as normal unsigned extension instead of temporary one

**Comment by dimdenGD** [comment]
This would break Chromium version of extension, modify pack.js script instead. Actually I think it already does that, so all you need is to just run pack.js to get actual Firefox version

**Comment by dimdenGD** [comment]
Though optional_permissions and other changes should be moved to pack.js so it'll only be on Firefox version

**Comment by Inclushe** [comment]
I moved the permissions and manifest scripts to just the Firefox version. Additionally, the packed Chrome extension was broken and missing the background script on your main branch, so I also fixed that.

**Pull request merged**
